services:
  mongodb:
    image: mongo:latest
    container_name: quizmaster-db
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=quizmaster

  redis:
    image: redis:latest
    container_name: quizmaster-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  mongodb_data:
  redis_data:
